### ISSUE TITLE
Some Tags Need Modifying

### ISSUE THREAD

**Issue by tvdk-sudoku** [GrimReaper2654/WACE-Database#65]
I feel like the following tags need to be modified:
Methods:
- Concavity (unnecessary)
- Z-scores (maybe?)
Spec:
- Component and Polar forms (maybe?)
- Absolute Values (vague - probably should be "Absolute Values Functions)
Physics:
- Add relativistic momentum and energy (kinetic and rest) as (preferably separate) tags under Special Relativity

**Comment by RJDJcool3** [comment]
I think 'Concavity' is an important tag as there are a decent chunk of questions where you need to find points of inflection/local max and mins and those questions require specific method. Its different to optimisation as it is more in relation to a graph rather than a function. You have to think about the general Methods student that doesn't take Spec. I've seen peers struggle with these questions/struggle meeting the requirements of this question.

Z-scores tag hasn't been applied yet which is why nothing comes up (I added it recently). I think it is important because you don't get formula for Z scores but you still need it to solve questions. Its also one of the trickier questions from the topic if you have never seen them before.

I think component and polar form should be kept. I didn't add either tag, but I still think they are worth keeping because you do find questions throughout complex numbers where you need to manipulate these forms in ways which need practice.

**Comment by RJDJcool3** [comment]
Absolute Value is under the function tag, it doesn't require function in the name as the tag becomes unnecessarily long. You can tell what it is about from a glance and therefore it works.

I agree with adding relativistic momentum and energy.

**Comment by RJDJcool3** [comment]
@GrimReaper2654 please review

**Comment by tvdk-sudoku** [comment]
However, the other tags under functions all say "blah blah functions" so I still think it should be "Absolute Value Functions".

**Comment by RJDJcool3** [comment]
Ah I see, I was getting a bit confused between the Methods and Spec tags (as Methods doesn't have that and then looking at Spec it didn't register in my brain). Yes, I agree that it could be a good change. I am ok with editing the tag if @GrimReaper2654 has no objections.

**Comment by GrimReaper2654** [comment]
I'll add polar and component form tags under vectors in spec. They will link to the same tags as the complex numbers ones but will appear under both sections

**Comment by GrimReaper2654** [comment]
Actually are there even polar form vectors in y12 spec?

**Comment by GrimReaper2654** [comment]
I've implemented a few of the changes, feel free to revert if you want

**Comment by tvdk-sudoku** [comment]
I don't think we need to have the polar and component tags full stop, but especially not under vectors as well. Also, I believe that adding a "Muon" tag is completely unnecessary.

**Comment by RJDJcool3** [comment]
Muon tag is completely unnecessary
I don't think we need polar or component tags under vectors either

I also believe that while yes, relativistic momentum and energy questions could deserve a tag, there is not enough of them to actually make it worthwhile to search for them. Especially having separate tags for each. I don't think it is necessary as most of the time, those questions will just be using the formula from the data booklet and not have any extra scope to the question.

**Comment by RJDJcool3** [comment]
If someone doesn't have an objection, I'll remove or combine the tags
